### ISSUE TITLE
no se está manejando el error en las peticiones que hace mongoose

### ISSUE THREAD

**Issue by jaquinterob** [EdisonOsorioPerez/manager-task#1]
https://github.com/EdisonOsorioPerez/manager-task/blob/a41b6a57dac630ae15d9670608e24273a699f80e/src/modules/users/users.service.ts#L16

**Comment by jaquinterob** [comment]
podrias hacer esto: 
`const userExist = await this.findUserByName(user.name).catch((error)=>{throw Error('error culpa de mongo')})`

**Comment by EdisonOsorioPerez** [comment]
Acabé de subir un pull request con una mejora para controlar los errores
